### ISSUE TITLE
Fails to build on MacOS 10.13.6 with brew gcc-8

### ISSUE THREAD

**Issue by jcnorris00** [awslabs/aws-c-common#528]
Configured with

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-8 -DBUILD_SHARED_LIBS=ON ~/src/aws-c-common

Fails with
<snip>/src/aws-c-common/source/posix/clock.c: In function 's_do_osx_loads':
<snip>/src/aws-c-common/source/posix/clock.c:60:20: error: ISO C forbids conversion of object pointer to function pointer type [-Werror=pedantic]
     s_gettime_fn = (int (*)(clockid_t __clock_id, struct timespec * __tp)) dlsym(RTLD_DEFAULT, "clock_gettime");
                    ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/aws-c-common.dir/source/posix/clock.c.o] Error 1
make[1]: *** [CMakeFiles/aws-c-common.dir/all] Error 2
make: *** [all] Error 2

Build succeeds if I use the compiler provided by Apple.
