### PR TITLE
Mac GCC 8 Build & Fixes

### LINKED ISSUE #528: Fails to build on MacOS 10.13.6 with brew gcc-8
Configured with

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-8 -DBUILD_SHARED_LIBS=ON ~/src/aws-c-common

Fails with
<snip>/src/aws-c-common/source/posix/clock.c: In function 's_do_osx_loads':
<snip>/src/aws-c-common/source/posix/clock.c:60:20: error: ISO C forbids conversion of object pointer to function pointer type [-Werror=pedantic]
     s_gettime_fn = (int (*)(clockid_t __clock_id, struct timespec * __tp)) dlsym(RTLD_DEFAULT, "clock_gettime");
                    ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/aws-c-common.dir/source/posix/clock.c.o] Error 1
make[1]: *** [CMakeFiles/aws-c-common.dir/all] Error 2
make: *** [all] Error 2

Build succeeds if I use the compiler provided by Apple.

### PR DESCRIPTION
**Pull request by ColdenCullen**
Fixes #528 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ColdenCullen** [comment]
Based on the travis failure:
https://travis-ci.org/awslabs/aws-c-common/jobs/602541923
It seems like this is a legitimate bug. We'll have to come back to this later, supporting GCC on macOS is not a priority right now.
