### ISSUE TITLE
musl builds are broken 

### ISSUE THREAD

**Issue by aduskett** [awslabs/aws-c-common#754]
source/posix/thread.c line 175 uses pthread_attr_setaffinity_np (introduced in commit 94efd6e062d2af5d9002674b60e1cbc9def8a581)  which MUSL does not have.

When compiling against a toolchain that uses musl, the following error occurs:
` error: implicit declaration of function ‘pthread_attr_setaffinity_np’; did you mean ‘pthread_setaffinity_np’?`

It should be a fairly straight-forward fix. I thought you guys would like to know!

**Comment by r-burns** [comment]
Can confirm, it's easy to reproduce this in nixpkgs:
`nix-build '<nixpkgs>' -A pkgsStatic.aws-c-common`

A trivial stub definition could allow this to compile, as done here: 
https://github.com/rexray/rexray/issues/719#issuecomment-279506056
Of course, it wouldn't actually set the affinity, so performance would be impacted vs. glibc.

**Comment by r-burns** [comment]
Fyi, this is resolved as of https://github.com/awslabs/aws-c-common/pull/766

**Comment by aduskett** [comment]
> Fyi, this is resolved as of #766

Great! Thank you so much!
